### PR TITLE
Crude fix for tvrage outage

### PR DESCRIPTION
**Pull request by CoryManson**
This is a crude fix to get tvrage ID's working again until a proper solution is found. Unfortunately I don't know python so this was just a lot of googling.

I found the trakt API the best solution to use as it has a lot of room to expand and should let us fix the "trending" module. Here's the API docs: http://docs.trakt.apiary.io/#

I've left my API key out, it should probably be a config item. see: trakt-api-key (https://trakt.tv/oauth/applications/new)

I believe this is a temporary fix as any new TV shows that trakt hasn't cached will probably still error. Needs full transition to trakt or tvdb.

### CODE REVIEW

**Comment by CoryManson** [comment]
I'm not sure why this has conflicts, might be because of my css fix from last year.

**Comment by Mirabis** [comment]
Yeh small change in style.css

**Comment by JudsonHat** [comment]
Thanks for this! However, I was getting this error when I try to start it.

```
root@user:~/usntssearch/NZBmegasearch# python /root/usntssearch/NZBmegasearch/mega2.py
Traceback (most recent call last):
  File "/usntssearch/NZBmegasearch/mega2.py", line 26, in <module>
    from ApiModule import ApiResponses
  File "/usntssearch/NZBmegasearch/ApiModule.py", line 280
    parsed_data = {'showtitle': ''}
              ^
IndentationError: expected an indented block
```

So I added an indented block at line 280. But now I am getting this error. I know almost nothing about python, so I am stuck here.

```
root@user:~/usntssearch/NZBmegasearch# python /root/usntssearch/NZBmegasearch/mega2.py daemon
Traceback (most recent call last):
  File "/usntssearch/NZBmegasearch/mega2.py", line 26, in <module>
    from ApiModule import ApiResponses
  File "/usntssearch/NZBmegasearch/ApiModule.py", line 287
    return parsed_data
SyntaxError: 'return' outside function
```

**Comment by Mirabis** [comment]
Those are indentation errors, check the spacings / tabs

**Comment by JudsonHat** [comment]
From lines 280-287, I deleted the spaces before the code and replaced it with indentations using the tab key.  After that, it started up fine.

**Comment by CoryManson** [comment]
Sorry bout the indentation errors. Github editor is somewhat lacking.

**Comment by Mirabis** [comment]
Fumbled a bit, so it doesn't show up as merged on the pull request - but changes are merged.

**Pull request closed without merging**
