### PR TITLE
Added tvdbid support. Rearranged search priority order

### PR DESCRIPTION
**Pull request by HackedServer**
I had to do some changes to Cozza38's code to get it to work for my SickRage install. I made a few other changes as well. I am not a python programmer, so please point out any errors.
-    I rearranged the elif order so that Query search came before Category search. This just makes sense, searching for show X in category X returned all shows.
-    I added an input to the getshowinfo function so that it can handle both tvrage and tvdb IDs. My SickRage calls using tvdbid, not rid. I cannot test, but rid should still work.
-    I added some information about the Trakt.tv API key to the README.md
-    I removed the .idea directory. I'm not sure what it was for.

### CODE REVIEW

**Comment by Mirabis** [comment]
The.idea folder was for PyCharm settings, back then I coded on my laptop while traveling and on home pc :)

**Comment by Mirabis** [comment]
Will have to test before I merge, probably 1-2 days :/

**Comment by HackedServer** [comment]
Have you gotten a chance to try it out?

[Someone said there is a typo](https://www.reddit.com/r/usenet/comments/3rlul8/cant_get_nzbmegasearch_to_send_files_to_nzbget/), but I'm not sure where.

I'm actively using my fork and haven't had issues.

**Comment by Mirabis** [comment]
No sorry ; (

But I will today,after class :)

**Pull request merged**
