### PR TITLE
Fix CP issue

### PR DESCRIPTION
**Pull request by Undeadhunter**
@Mirabis 

Sorry, messed up quite a bit with Pull Requests ... instead of merging my own fork I merged yours ... I blame the desktop tool... 

Can you review and merge in master ?

### CODE REVIEW

**Comment by Mirabis** [comment]
Testing with Sonarr now

-- No luck with Sonarr/NzbDrone - havn't confirmed with Couchpotato yet..

Changes seem okay though

**Comment by Undeadhunter** [comment]
Is searching having issues or rss? In any case I'll take a look as well,
would be strange cp works but sonarr won't...

Update:
Tried it with Sonarr, works fine here, can you do a print out of the log of nzbmegasearch?

**Comment by Undeadhunter** [comment]
Search seems to work .. sometimes
RSS is pretty much broken, only gets wombles it looks like, but not the other configured

**Comment by Mirabis** [comment]
Hmm tried manual search, but I only get 1 result + sonarr can't map it back to a show

**Comment by Undeadhunter** [comment]
Check your Sonarr log, and open the link it searches for. That's where I would start figuring out where it's going wrong.

**Comment by Mirabis** [comment]
Today 'search' started working :p will have to wait till weekend to debug more.
https://gyazo.com/e62bd045675dffb64f2a90a2e912f506

**Pull request merged**
